version: "3.1"

services:
  db:
    container_name: dbTMB
    image: sameersbn/postgresql:10-2
    environment:
      POSTGRES_DB: "TeamMeetings"
      POSTGRES_USER: "dmitriy"
      POSTGRES_PASSWORD: "dmitriy"
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: botTNB
    build:
      context: TeamMeetings
    command: python bot.py
    restart: always
    networks:
      - botnet
    depends_on:
      - db

networks:
  botnet:
    driver: bridge