version: "3.1"

services:
  db:
    container_name: databaseTM
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres1
    restart: always
    ports:
      - '5432:5432'
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: botTM
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - botnet
    volumes:
      - .:/TeamMeetings
    depends_on:
      - db

networks:
  botnet:
    driver: bridge