version: "3.1"

services:
  db:
    container_name: databaseTM
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: always
    ports:
      - '5432:5432'
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  redis:
    image: redis:5-alpine
    restart: on-failure
    volumes:
      - ./storage/redis/data:/data
    networks:
      - botnet

  tgbot:
    container_name: botTM
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - botnet
    volumes:
      - .:/TeamMeetings
    depends_on:
      - db
    env_file:
      - ".env"

networks:
  botnet:
    driver: bridge